### ISSUE TITLE
Question about the evaluation on temporal warping error

### ISSUE THREAD

**Issue by ZhouYiiFeng** [phoenix104104/fast_blind_video_consistency#16]
Dear author, i found that in your paper's table 2, you said your `temporal warping error` , for example, `WCT/wave` is equal to` 0.027`, but i download your results and notice that in the `WCT/wave/DAVIS/Warp_error.txt` the `average warping error ` is 0.003591. I'm so confused about that, could you please help me out? thanx!

**Comment by mengxiangyudlut** [comment]
I have the same question.

**Comment by linhl97** [comment]
I'm also confused about it，they're not even the same order of magnitude

**Comment by phoenix104104** [comment]
The results reported in the paper is from a model trained with older Pytorch version, and I have lost the old checkpoint files. Please use the pretrained model in this repo or your own re-trained model for reporting the results. Thanks.

**Comment by ZhouYiiFeng** [comment]
Some results are provided in my project (TDMS-Net) which refers to this work. Again, thanks for the contribution of @phoenix104104
