### ISSUE TITLE
About download the pretrained models.

### ISSUE THREAD

**Issue by MasterHow** [phoenix104104/fast_blind_video_consistency#22]
Dear author, 

Could you please consider uploading the pre-trained model to the network disk, the page of the laboratory website seems to be invalid, and now the pre-trained model cannot be downloaded from the laboratory website. QAQ

Thanks for your contribution. : )

![image](https://user-images.githubusercontent.com/44900255/194742188-847eb890-bc54-4d06-8162-acc14e90f8f7.png)

**Comment by jiahui1688** [comment]
I met the same problem, can you tell me how to solve it?

**Comment by MasterHow** [comment]
> 

Hi, I use the pretrained FlowNet2 and solved this problem. see  (https://github.com/NVIDIA/flownet2-pytorch)

**Comment by Vivien888** [comment]
I have seen the pretrained FlowNet2, but still have no idea to solve this problem. Could you tell me how you solved this problem with the pretrained FlowNet2? Thank you very much.
