### ISSUE TITLE
Inputs to the model

### ISSUE THREAD

**Issue by musicrainie** [phoenix104104/fast_blind_video_consistency#3]
Thanks for your great works.
In this code, the inputs to the model is (frame_p2, frame_o1, frame_i2, frame_o1) and the provided results comply with it, which seems not to be consistent with the paper if I don't misunderstand the details. Is it just the case that frame_i1 is not used as an input to the model, which means it doesn't need to appear at all in the test phase?

**Comment by phoenix104104** [comment]
Hi, you are right. The inputs to the model should be (frame_p2, frame_o1, frame_i2, **frame_i1**). frame_i1 should be used in both training and testing. I will update the code and model.

**Comment by phoenix104104** [comment]
Code and model are updated.
