### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by liuchen1912** [phoenix104104/fast_blind_video_consistency#4]
Hello, thanks for your great work! I have passed the compilation phase and have downloaded the pre-trained model, when I run test_pretrained.py it occurs the error"No module named 'FlowNetC'", my pyTorch version is 0.4.0, cuda 9.0 and cudnn 7.0. How can I solve the problem? Please help me, thank you! @phoenix104104

**Comment by phoenix104104** [comment]
I can't reproduce your error. Could you share the full error message?

**Comment by phoenix104104** [comment]
See Issue #5.
