### ISSUE TITLE
Test error and solution 

### ISSUE THREAD

**Issue by xuangu-fang** [phoenix104104/fast_blind_video_consistency#5]
I really appreciate your nice work,  but met the similar problems as Issue[[ NO.4]](https://github.com/phoenix104104/fast_blind_video_consistency/issues/4), when I tried to apply the pre-trained model on my owl data. 

The problem comes from the **package import commands** in **all .py files in your  "network" folder**. For example, in FlowNet2.py, you try to import FlowNetC.py using "import FlowNetC" directly, but it's doomed to fail with error information "There is no module named FlowNetC". Thus, you should use "**from . import FlowNetC"** instead to solve it.

**Comment by phoenix104104** [comment]
Cool! Thanks for pointing out.
