### ISSUE TITLE
About the non-occlusion-mask presented in fig.2 in the paper

### ISSUE THREAD

**Issue by Nash2325138** [phoenix104104/fast_blind_video_consistency#7]
Hello :D

Recently, I want to implement the short-term temporal loss proposed in this paper. But I find our non-occlusion-mask has the not-moving regions with high values (bright) and moving regions with low values (dark), which seems contrary to the picture M_{t->t-1} presented in figure 2 of your paper.
I want to ask if it is normal because I'm afraid I might have a wrong implementation.

Thank you very much :)

**Comment by phoenix104104** [comment]
Figure 2 of my paper is wrong. The mask is "occlusion" mask and I should invert it.
Your implementation is correct.

**Comment by mengxiangyudlut** [comment]
what is the meaning of occlusion
